### ISSUE TITLE
Can I use it on unix based systems?

### ISSUE THREAD

**Issue by vivacenontroppo** [MarkTiedemann/cisco-vpn#4]
Hi,

I'm sorry if that's a silly question but is there a way to run it on MacOS or Ubuntu? I'm using Cisco AnyConnect Client on MacOS because that's the only way company allows it and wan't to make sql query over vpn.
That's the result:
```vpncli.exe: cannot execute binary file```

MacOS / node / cisco-vpn package - up to date.

**Comment by MarkTiedemann** [comment]
Yes, you should be able to use this module on MacOS; though I have not tested it yet.

It is wrapping Cisco's VPN CLI which is located at `C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\vpncli.exe` on Windows and `/opt/cisco/anyconnect/bin/vpn` on MacOS with the default installation.

This module has an [option](https://github.com/MarkTiedemann/cisco-vpn#requirecisco-vpnoptions) called `exe` which you can use to provide the location of the VPN CLI.

I hope this helps.
